//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDichVuDiChoThueCDIO4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int CTDH_ID { get; set; }
        public Nullable<int> DH_ID { get; set; }
        public Nullable<int> SP_ID { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> SOLUONGSP { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public string HINHANH { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
