//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDichVuDiChoThueCDIO4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int DG_ID { get; set; }
        public Nullable<int> DIEM { get; set; }
        public Nullable<int> SP_ID { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
