//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDichVuDiChoThueCDIO4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
    
        public int DH_ID { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<double> PHIGIAOHANG { get; set; }
        public Nullable<int> GH_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> TK_ID { get; set; }
        public string HOTEN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> DUYET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual GIAOHANG GIAOHANG { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
