//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDichVuDiChoThueCDIO4.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GIOHANG
    {
        public int GIOHANG_ID { get; set; }
        public string TENSP { get; set; }
        public Nullable<double> GIASP { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> TK_ID { get; set; }
        public Nullable<int> SP_ID { get; set; }

        public int thanhtien { get; set; }
        public GIOHANG()
        {

        }
        public GIOHANG(int iSP_ID, int id)
        {
            using (QLDICHOTHUEEntities2 db = new QLDICHOTHUEEntities2())
            {
                this.SP_ID = iSP_ID;
                this.TENSP = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).TENSP;
                this.GIASP = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).GIASP;
                this.HINHANH = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).HINHANH;
                this.SOLUONG = 1;

                this.TK_ID = id;
                this.thanhtien = (int)(GIASP * SOLUONG);
            }
        }

        public GIOHANG(int iSP_ID, int id, int soluong)
        {
            using (QLDICHOTHUEEntities2 db = new QLDICHOTHUEEntities2())
            {
                this.SP_ID = iSP_ID;
                this.TENSP = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).TENSP;
                this.GIASP = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).GIASP;
                this.HINHANH = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).HINHANH;
                this.SOLUONG = soluong;

                this.TK_ID = id;
                this.thanhtien = (int)(this.GIASP * this.SOLUONG);
            }
        }


        public virtual SANPHAM SANPHAM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
